### ISSUE TITLE
Ignore users feature

### ISSUE THREAD

**Issue by ArielJGS** [aticie/ronnia#13]
Hello, I use your bot on twitch, honestly it always work great but I was wondering if it would be possible to add a feature to ignore some users, it would be useful so you can ignore other bots, I currently have an !np command and when my bot replies your bot takes the request

**Comment by aticie** [comment]
It should be closed with #14.

To set up excluded users, I need to make changes to the website. In the meantime, you can tell me which users you want to block, and I can add them to database for you manually. (Website changes may take some time)
