### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by tylort69** [aticie/ronnia#38]
https://gyazo.com/c171cd3fb110d40f200500b1f3f46c53

C:\Users\Tylor>cd Downloads

C:\Users\Tylor\Downloads>cd ronnia-1.4.7

C:\Users\Tylor\Downloads\ronnia-1.4.7>cd ronnia-1.4.7

C:\Users\Tylor\Downloads\ronnia-1.4.7\ronnia-1.4.7>cd src

C:\Users\Tylor\Downloads\ronnia-1.4.7\ronnia-1.4.7\src>python main.py
Traceback (most recent call last):
  File "C:\Users\Tylor\Downloads\ronnia-1.4.7\ronnia-1.4.7\src\main.py", line 7, in <module>
    logger.setLevel(os.getenv('LOG_LEVEL').upper())
AttributeError: 'NoneType' object has no attribute 'upper'

C:\Users\Tylor>python -VV
Python 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)]

C:\Users\Tylor>pip --version
pip 21.3.1 from C:\Users\Tylor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip (python 3.9)

C:\Users\Tylor\Downloads\ronnia-1.4.7\ronnia-1.4.7\src>pip install -r requirements.txt
Requirement already satisfied: twitchio==2.0.6 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 1)) (2.0.6)
Requirement already satisfied: irc>=19.0.0 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 2)) (19.0.1)
Requirement already satisfied: aiohttp>=3.7.0 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 3)) (3.7.4.post0)
Requirement already satisfied: tempora>=1.6 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from irc>=19.0.0->-r requirements.txt (line 2)) (4.1.2)
Requirement already satisfied: jaraco.collections in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from irc>=19.0.0->-r requirements.txt (line 2)) (3.4.0)
Requirement already satisfied: more-itertools in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from irc>=19.0.0->-r requirements.txt (line 2)) (8.11.0)
Requirement already satisfied: jaraco.functools>=1.20 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from irc>=19.0.0->-r requirements.txt (line 2)) (3.4.0)
Requirement already satisfied: jaraco.text in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from irc>=19.0.0->-r requirements.txt (line 2)) (3.6.0)
Requirement already satisfied: jaraco.stream in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from irc>=19.0.0->-r requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: pytz in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from irc>=19.0.0->-r requirements.txt (line 2)) (2021.3)
Requirement already satisfied: jaraco.logging in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from irc>=19.0.0->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp>=3.7.0->-r requirements.txt (line 3)) (21.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp>=3.7.0->-r requirements.txt (line 3)) (1.7.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp>=3.7.0->-r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp>=3.7.0->-r requirements.txt (line 3)) (3.7.4.3)
Requirement already satisfied: chardet<5.0,>=2.0 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp>=3.7.0->-r requirements.txt (line 3)) (4.0.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp>=3.7.0->-r requirements.txt (line 3)) (5.2.0)
Requirement already satisfied: idna>=2.0 in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from yarl<2.0,>=1.0->aiohttp>=3.7.0->-r requirements.txt (line 3)) (2.10)
Requirement already satisfied: jaraco.classes in c:\users\tylor\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from jaraco.collections->irc>=19.0.0->-r requirements.txt (line 2)) (3.2.1)

**Comment by aticie** [comment]
https://github.com/aticie/ronnia#hosting-the-bot

You need to set these environment variables in order to work.

**Comment by aticie** [comment]
There's no easy way of initializing environment variables on Windows instead of setting them 1 by 1, so I would suggest using Docker.

https://github.com/aticie/ronnia#build-and-run

You can write your .env file and pass it to container with `docker run --name ronnia --env-file .env ronnia-bot`
