### ISSUE TITLE
Ronnia conflict with osu-np bot

### ISSUE THREAD

**Issue by miyuki-ts** [aticie/ronnia#49]
The problem is if user use !np command the osu-np will do this in chat:

@!sender!, Now Playing: !artist! - !title! [!version!] Mapped by !creator!, Download: https://osu.ppy.sh/beatmapsets/!set-id!#osu/!id!
@kamythol, Now Playing: LiSA - Rock-Mode [mode: 180BPM] Mapped by Smokeman, Download: https://osu.ppy.sh/beatmapsets/240756#osu/556307

but since ronnia check chat for beatmap links it will send !np as Now playing as a request beatmap
LiSA - Rock-Mode [mode: 180BPM] - Request sent!

Either there need a condition that check if it's an !np command or even a request.

and then a option to change what the String output in chat would be. but that is optional, since it's your project and bot not mine :D

**Comment by aticie** [comment]
You can exclude users from the dashboard. If you add np-bot's nickname to the list, ronnia should ignore it.

**Comment by aticie** [comment]
By default, the bot should ignore messages from your own account. You should disable test mode. If that still doesn't work, you can try adding your own username to excluded users. 
![IMG_0402](https://github.com/aticie/ronnia/assets/25616662/4f6940d4-2cf3-4fdf-91ff-14cc403da6ee)

**Comment by aticie** [comment]
Are you using https://github.com/aticie/ronnia-selfhost ?

**Comment by aticie** [comment]
It's a bit different with the selfhost bot. 

Just make sure to have:
`listen-to-self-message = False`

If that does not work, try adding your twitch username to:
`excluded-users = `

**Comment by aticie** [comment]
> so right now, !np works if i use my own account, and since i disable ronnia for streamer my own account it won't work but !np and ronnia does not work if i do it from a new account idk why ![image](https://private-user-images.githubusercontent.com/93956624/292495813-38828275-93f6-4bbe-9d53-79e037463e8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTE3MDEsIm5iZiI6MTcwMzI1MTQwMSwicGF0aCI6Ii85Mzk1NjYyNC8yOTI0OTU4MTMtMzg4MjgyNzUtOTNmNi00YmJlLTlkNTMtNzllMDM3NDYzZThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEzMjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYTM3NTY4OTI1MjZjNjM0Zjc2MDM1MDg0MDMxMjc5NjZkODc2MmRlYmRhNTYyZjdkYWQ3ODUzM2E2OGYzMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b3RVayTXRAOc2DhAcT9vR_kqiULcxFJGJq7SGNU-bfA)

The error text right here is informative.

For example, if you are the ronnia-selfhost bot and osu-np bot on the same twitch account called `wei`, any messages coming from `wei` will be ignored by ronnia. This is what you wanted, right? Since you don't want np messages to become requests, it is ignoring messages from the `wei` account.

**Comment by aticie** [comment]
Could you give an example of what's happening exactly? Please include screenshots of what you are doing, and what you want to achieve.

**Comment by aticie** [comment]
I can't help with np-bot. You could try raising the issue on their repository [OsuNowPlaying](https://github.com/TheOmyNomy/OsuNowPlaying) ?

From what I see, you have `listen-to-self-message = True` in your settings. And ronnia is working as expected.

> I try to send a beatmap link in chat on a different account called chuuflow not my main account
> ![image](https://private-user-images.githubusercontent.com/93956624/292498154-a3fa8e2a-ef11-491f-a5e1-4dc0179f4ce5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTI5OTMsIm5iZiI6MTcwMzI1MjY5MywicGF0aCI6Ii85Mzk1NjYyNC8yOTI0OTgxNTQtYTNmYThlMmEtZWYxMS00OTFmLWE1ZTEtNGRjMDE3OWY0Y2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEzNDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YmUwZDRkYTcyNWMxN2QxMmIzYzUxNGQzMmZkZWU5YTFlZTc0YzliNWZmYmFmNTZhODY3MjM3MjhiNGNjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._GI9nU_HdiLjq47zPQ_Nv_Nuuka7eXWgulXFaLYCnLI)

Ronnia should respond to the last message on here. If it doesn't, could you show what it outputs to the terminal after you send a beatmap link from `chuuflow` account?

**Comment by aticie** [comment]
Do you see any logs for any other user's (for example NightBot's) messages?

**Comment by aticie** [comment]
It seems like for some reason both Ronnia and the np bot doesn't see the messages on your channel. Please double-check your TMI token and twitch username.
